// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9kVVoW-reMPceSQ-QJbE9tXgXQI1MYAk',
    appId: '1:603928847813:web:65b6ac601155837ddd17ac',
    messagingSenderId: '603928847813',
    projectId: 'orbit-b9d13',
    authDomain: 'orbit-b9d13.firebaseapp.com',
    storageBucket: 'orbit-b9d13.firebasestorage.app',
    measurementId: 'G-9EXJPX4G64',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9Hhwu3zy1x7QVS1liMQjI9T3QdGS3AmQ',
    appId: '1:603928847813:android:d3035f9852f40cd7dd17ac',
    messagingSenderId: '603928847813',
    projectId: 'orbit-b9d13',
    storageBucket: 'orbit-b9d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClffncURdLl3emN35MPUrkRjP1Ocb5I0w',
    appId: '1:603928847813:ios:d44358bef0d4d497dd17ac',
    messagingSenderId: '603928847813',
    projectId: 'orbit-b9d13',
    storageBucket: 'orbit-b9d13.firebasestorage.app',
    iosBundleId: 'com.example.habbitTrackingApp',
  );
}
